apiVersion: v1
kind: Secret
metadata:
  name: wanderlust-secrets
  namespace: wanderlust
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL3VzZXI6cGFzc0BtYWluZGI6MjcwMTcvcHJvamVjdA==
  JWT_SECRET: c3VwZXJzZWNyZXRrZXk=
